config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'
  post "tasks", to: "tasks#create"

  get 'tasks/new', to: 'tasks#new'
  get 'tasks/:id', to: 'tasks#show', as: :task

  get 'tasks/:id/edit', to: 'tasks#edit', as: :task_edit
  patch 'tasks/:id', to:'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy'

  # resources :tasks, only: [:create, :index, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

    def index 
      # raise
      @tasks = Task.all
    end
  
    def show
      @task = Task.find(params[:id])
    end
  
    def new 
      @task = Task.new
    end
  
    def create
      @task = Task.new(task_params)
      @task.save
  
      redirect_to task_path(@task)
    end
  
    def edit
      @task = Task.find(params[:id])
    end
  
    def update
      @task = Task.find(params[:id])
      @task.update(task_params)
  
      redirect_to tasks_path
    end
  
    def destroy
      # raise
      @task = Task.find(params[:id])
      @task.destroy
      redirect_to tasks_path
    end
  
    private
  
    
    def task_params
      params.require(:task).permit(:title, :details)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <%=f.label :title %>
  <%=f.text_field :title %>
  <%=f.label :details %>
  <%=f.text_field :details %>
  <%=f.submit%>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit a task</h1>

<%= form_for(@task) do |f| %>
    <%=f.label :title %>
  <%=f.text_field :title %>
  <%=f.label :details %>
  <%=f.text_field :details %>
  <%=f.submit%>
<% end %>

<%=  link_to 'Back', tasks_path%>

app/views/tasks/index.html.erb
<h1>Here are your tasks for today</h1>


<% @tasks.each do |task|%>
  <li><input type="checkbox" value='<%=%>'>
  <%=link_to task.title, task_path(task)%>
  <%= link_to  "Delete", task_path(task), method: :delete %>
<%end%>
</ul>

<h3>Do you want to create a new task ?</h3>

<%= link_to  "Create a new task", tasks_new_path %>

app/views/tasks/new.html.erb
<h1>Here are your tasks for today</h1>

<%= form_for(@task) do |f| %>
  <%=f.label :title %>
  <%=f.text_field :title %>
  <br/>
  <%=f.label :details %>
  <%=f.text_field :details %>
  <br/>
  <%=f.submit%>
<% end %>

<%=  link_to 'Back', tasks_path%>

app/views/tasks/show.html.erb
<h1>Let's focus on one task</h1>

<%= link_to  "Edit the task", task_edit_path(@task.id) %> 
<h2>Your task : <%= @task.title%></h2>
<p>You have to do : <%= @task.details%></p>

<%=  link_to 'Back', tasks_path%>